name: Get and store basedata from BPS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Get and store base data from BPS
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          BPS_API_KEY: ${{ secrets.BPS_API_KEY }}
        run: |
          python src/indonesia_in_data/parse_basedata_bps.py
